### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by Cryaaa** [GuignardLab/napari-spatial-correlation-plotter#2]
Dear Repository Owners,
I was reading your preprint and was happy to see that you open sourced your code, but going through it I noticed that there are large parts of it that were taken from the [napari-cluster-plotter](https://github.com/BiAPoL/napari-clusters-plotter?tab=readme-ov-file), albeit with some modification. The colormap generation is identical [napari-cluster-plotter colormap](https://github.com/BiAPoL/napari-clusters-plotter/blob/c7bae7b930c64c278fd3b188302c7ec3223c01cf/napari_clusters_plotter/_utilities.py#L422-L681), [napari-spatial-correlation-plottter colormap](https://github.com/GuignardLab/napari-spatial-correlation-plotter/blob/main/src/napari_spatial_correlation_plotter/_nice_colormap.py) as well as some functions that were present in [older versions of the cluster plotter](https://github.com/BiAPoL/napari-clusters-plotter/releases/tag/0.7.0), that are identical to lines of code in this repository: [here](https://github.com/GuignardLab/napari-spatial-correlation-plotter/blob/36fc6fd1960f26aab151c7c3dd4bad6bd4815384/src/napari_spatial_correlation_plotter/_widget.py#L576C5-L599C10) and [here](https://github.com/GuignardLab/napari-spatial-correlation-plotter/blob/36fc6fd1960f26aab151c7c3dd4bad6bd4815384/src/napari_spatial_correlation_plotter/_widget.py#L959-L1038)

The napari-cluster-plotter is released under the BSD-3 License, which permits copying and reusing the code, given that the Copyright License including authors is reproduced as stated [here](https://github.com/BiAPoL/napari-clusters-plotter?tab=BSD-3-Clause-1-ov-file). We ask you to add the copyright license to the respective files, where code was reused by adding a header reading:

"""
Copyright (c) 2022, DFG Cluster of Excellence "Physics of Life" TU Dresden: Robert Haase, Laura Zigutyte, Marcello Zoccoler, Ryan Savill, Johannes Müller and Max Planck Institute of Molecular Physiology Dortmund: Thorsten Wagner
"""

as well as maintaining the copyright license during further development and distribution. We also would be grateful if you cite the [zenodo DOI](https://zenodo.org/records/8238460) as inspiration for your plugin in the manuscript. Thank you in advance! 

Ryan Savill

**Comment by jules-vanaret** [comment]
Dear Ryan,
I unfortunately missed this issue and thus only partially rectified my mistake as explained in my email. I just pushed and released a new version with the headers, and an updated preprint should be uploaded in the new weeks.
Again, I apologize for the oversight and any inconvenience this may have caused. I'll keep this issue opened for now, please feel free to notify me if I have missed anything.
Best,
 Jules Vanaret

**Comment by Cryaaa** [comment]
Hey Jules,
No problem, these things can happen. Going through the files I think everything is fine and in agreement with the license. Thank you for taking action so quickly and updating the preprint as well! All the best for your publication and have a nice weekend.

Best, Ryan
